#!/bin/bash
source grade_utils
printf "\n\n### Grade Physical Number part A ###\n"
make -f Makefile clean

i=0
printf "\n\n### Check $i: our demo program should compile with your class\n"
grade_command make -f Makefile demo
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: our demo program should run without errors\n"
grade_command ./demo
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: our test program should compile with your class\n"
grade_command make -f Makefile test
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: our test program should run (may have errors)\n"
grade_command ./test
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: your test program should compile with our class\n"
cp OurPhysicalNumber.h PhysicalNumber.h 
cp OurUnit.h Unit.h 
grade_command make -f Makefile your_test_our_class
grades[$i]=$grade
swap OurPhysicalNumber.h PhysicalNumber.h 
swap OurUnit.h Unit.h 
printf "### Grade $i: ${grades[$i]}\n"

# from here: https://stackoverflow.com/a/31653407/827927
IFS='+' average_grade=$(echo "scale=1;(${grades[*]})/${#grades[@]}"|bc)
signature="bayHogkjxySS7cqMI54xjKiuF4l2_5"
printf "\n\n*** Average grade: $average_grade $signature ***\n\n"

make -f Makefile --silent clean
